name: fast_app_badge
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/koji-1009/fast_app_badge

environment:
  sdk: ^3.10.0
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  objective_c: ^9.2.1

dev_dependencies:
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
